version: '3'

vars:
  GREETING: Hello, World!

tasks:
  submodules:
    cmds:
      - git submodule update --init --recursive
    silent: true

  kwok:*:create:
    vars:
      PROJECT_NAME: "{{index .MATCH 0}}"
    preconditions:
      - sh: |
          if task kwok:{{.PROJECT_NAME}}:ps | grep -q "{{.PROJECT_NAME}}-kwok"; then
            echo "{{.PROJECT_NAME}} already exists"
            exit 1
          fi
          exit 0
        msg: "{{.PROJECT_NAME}} already exists"
    cmds:
      - task: kwok:{{.PROJECT_NAME}}:up -d
      - echo "{{.PROJECT_NAME}} created"

  kwok:*:delete:
    vars:
      PROJECT_NAME: "{{index .MATCH 0}}"
    cmds:
      - task: kwok:{{.PROJECT_NAME}}:down --volumes --remove-orphans

  kwok:*:*:
    vars:
      PROJECT_NAME: "{{index .MATCH 0}}"
      CLI_ARGS: "{{index .MATCH 1}}"
    cmds:
      - |
        docker compose \
          -f mock/compose.yaml \
          --project-name {{.PROJECT_NAME}} \
          {{.CLI_ARGS}}
  
  kind:*:*:
    vars:
      CLUSTER_NAME: "{{index .MATCH 0}}"
      ACTION: "{{index .MATCH 1}}"
    cmds:
      - kind {{.ACTION}} cluster --name {{.CLUSTER_NAME}}

  rocketchat:kwok:*:
    vars:
      MODE: "{{index .MATCH 0}}"
      PROJECT_NAME: "kwok-{{.MODE}}"
      KUBECONFIG_ENV:
        sh: mktemp
      KWOK_PORT:
        sh: |
          if [[ "{{.MODE}}" == "microservices" ]]; then
            echo 8081
          else
            echo 8080
          fi
      CLUSTER_NAME: "kwok-{{.MODE}}"
    env:
      KWOK_PORT: "{{.KWOK_PORT}}"

    cmds:
      - |
        if ! task kwok:{{.CLUSTER_NAME}}:ps | grep -q "{{.CLUSTER_NAME}}"; then
          task kwok:{{.CLUSTER_NAME}}:create
        fi
      - defer: task kwok:{{.CLUSTER_NAME}}:delete
      - sed "s/8080/${KWOK_PORT:-8080}/g" mock/kubeconfig.yaml > "{{.KUBECONFIG_ENV}}"
      - KUBECONFIG="{{.KUBECONFIG_ENV}}" ./rocketchat/tests/run.bash {{.MODE}}

  rocketchat:kind:*:
    vars:
      MODE: "{{index .MATCH 0}}"
      CLUSTER_NAME: "kind-{{.MODE}}"
    cmds:
      - task kind:{{.CLUSTER_NAME}}:create
      - defer: task kind:{{.CLUSTER_NAME}}:delete
      - ./rocketchat/tests/run.bash {{.MODE}}

    
  e2e:rocketchat:*:*:
    vars:
      TOOL: "{{index .MATCH 0}}"
      MODE: "{{index .MATCH 1}}"
    cmds:
      - task: clean
      - task: rocketchat:{{.TOOL}}:{{.MODE}}

  clean:
    cmds:
      - find . -name "*.tgz" -delete