{
 "title": "Rocket.Chat MicroService Metrics",
 "description": "A specialized dashboard for monitoring Rocket.Chat deployments using the microservices architecture. This dashboard provides detailed metrics on each microservice component, allowing for granular monitoring and troubleshooting of the distributed Rocket.Chat deployments.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(rocketchat_info,job)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(rocketchat_info{job=\"$Job\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Workspace",
    "query": {
     "query": "label_values(rocketchat_agents_total{cluster=~\"$Cluster\", job=\"$Job\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_nodes_total{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_services_total{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(moleculer_registry_actions_total{namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_events_total{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_request_total{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_request_error_total{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.9, irate(moleculer_request_time_rate{namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(moleculer_request_total{namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(moleculer_request_time_rate{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(moleculer_request_total_rate{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(irate(moleculer_request_error_total_rate{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(moleculer_request_time_sum{namespace=~\"$namespace\"}[2m]) / rate(moleculer_request_time_count{namespace=~\"$namespace\"}[2m])) by (action, type)",
     "legendFormat": "{{action}} ({{type}})"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "moleculer_request_total_rate{namespace=~\"$namespace\"}",
     "legendFormat": "{{action}} ({{nodeID}})"
    }
   ]
  },
  {
   "title": "Current Concurrent Users",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rocketchat_users_online{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "DDP Streamer Connected Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "users_connected{namespace=~\"$namespace\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Error types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action, errorName) (irate(moleculer_request_error_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{action}} - {{errorName}}"
    }
   ]
  },
  {
   "title": "Broadcasts rate by event",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(moleculer_event_broadcast_local_total{namespace=~\"$namespace\"}[5m])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Request totals rate by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_total{namespace=~\"$namespace\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Request totals rate by microservice",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_total{namespace=~\"$namespace\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Service Request rate by node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "moleculer_request_total_rate{namespace=~\"$namespace\"}",
     "legendFormat": "{{nodeID}}-{{action}}"
    }
   ]
  },
  {
   "title": "Request totals by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(moleculer_request_total{namespace=~\"$namespace\"}) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Service Requests by node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "moleculer_request_total{namespace=~\"$namespace\"}",
     "legendFormat": "{{nodeID}}-{{action}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 73 } },
  {
   "title": "Online nodes according to each node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "moleculer_registry_nodes_online_total{namespace=~\"$namespace\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Online nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_nodes_total{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}