{
 "title": "Rocket.Chat MongoDB 8 Performance Overview",
 "description": "Rocket.Chat MongoDB Performance Overview",
 "tags": [
  "use1",
  "workspace"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   { "name": "Replica", "query": { "query": "label_values(mongodb_up,pod)" } },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{pod=~\"$Replica\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mongodb_uptime{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mongodb_connections_available{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReplicaSet Members",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    count(count by(pod)(mongodb_members_state))"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_connections{pod=~\"$Replica\", state=\"active\"}\r\nor\r\nmongodb_connections_active{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}} - {{state}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "WiredTiger Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{pod=~\"$Replica\"}[$__rate_interval])\r\nor\r\n(\r\n    rate(mongodb_wiredTiger_cache_bytes_written_from_cache{pod=~\"$Replica\"}[$__rate_interval])\r\n    +\r\n    rate(mongodb_wiredTiger_cache_bytes_read_into_cache{pod=~\"$Replica\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{pod}} - {{type}}"
    }
   ]
  },
  {
   "title": "Cache Pages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_wiredTiger_cache_pages_written_from_cache{pod=~\"$Replica\"}[$__rate_interval])\r\n+\r\nrate(mongodb_wiredTiger_cache_pages_read_into_cache{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{type}}"
    }
   ]
  },
  {
   "title": "Operations queued due to locks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mongodb_globalLock_currentQueue_total{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}} - {{count_type}}"
    }
   ]
  },
  {
   "title": "Rate of Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_network_numRequests{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Oplog write intent locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_locks_oplog_acquireCount_r{pod=~\"$Replica\"}[$__rate_interval])\r\nor\r\nrate(mongodb_locks_oplog_acquireCount_w{pod=~\"$Replica\"}[$__rate_interval])\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache evicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{pod=~\"$Replica\"}[$__rate_interval])\r\nor\r\nrate(mongodb_wiredTiger_block_cache_evicted_blocks{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "createIndex command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(mongodb_ss_metrics_commands_createIndexes_total{pod=~\"$Replica\"}[$__rate_interval]))\r\nor\r\nsum by(pod) (rate(mongodb_metrics_commands_createIndexes_total{pod=~\"$Replica\"}[$__rate_interval]))\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time acquiring locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_locks_Global_timeAcquiringMicros_w{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU cores used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{instance=~\"$Instance.*\", mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=~\"$Instance.*\"}[$__rate_interval])) by (instance, device)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Reads Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(node_disk_reads_completed_total{instance=~\"$Instance.*\",}[$__rate_interval])) by(instance, device)",
     "legendFormat": "{{instance}} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$Instance.*\"}[$__rate_interval])) by(instance, device)",
     "legendFormat": "{{instance}} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (rate(node_disk_write_time_seconds_total{instance=~\"$Instance.*\"}[$__rate_interval])) / sum by(instance, device)(rate(node_disk_writes_completed_total{instance=~\"$Instance.*\"}[$__rate_interval]))",
     "legendFormat": "READ - {{instance}} - {{device}}"
    },
    {
     "expr": "sum by(instance, device)(rate(node_disk_read_time_seconds_total{instance=~\"$Instance.*\"}[$__rate_interval])) / sum by(instance, device)(rate(node_disk_reads_completed_total{instance=~\"$Instance.*\"}[$__rate_interval]))",
     "legendFormat": "WRITE - {{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_bytesIn{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "Inbount {{pod}}"
    },
    {
     "expr": "rate(mongodb_network_bytesOut{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "Outbound {{pod}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(container_memory_usage_bytes{pod=~\"$Replica\", container!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum  by(pod) (rate(mongodb_opcounters_command{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum  by(pod) (rate(mongodb_opcounters_delete{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum  by(pod) (rate(mongodb_opcounters_getmore{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum  by(pod) (rate(mongodb_opcounters_insert{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum  by(pod) (rate(mongodb_opcounters_query{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum  by(pod) (rate(mongodb_opcounters_update{pod=~\"$Replica\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(mongodb_metrics_document_deleted{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_document_inserted{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_document_returned{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_document_updated{pod=~\"$Replica\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(mongodb_metrics_queryExecutor_collectionScans_nonTailable{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_queryExecutor_collectionScans_total{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_queryExecutor_profiler_collectionScans_nonTailable{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_queryExecutor_profiler_collectionScans_tailable{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_queryExecutor_profiler_collectionScans_total{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_queryExecutor_scanned{pod=~\"$Replica\"}[$__rate_interval]))\r\n+\r\nsum by(pod) (rate(mongodb_metrics_queryExecutor_scannedObjects{pod=~\"$Replica\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{pod=~\"$Replica\"}[$__rate_interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }, "repeat": "env" },
  {
   "title": "Member Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by(member_idx) (mongodb_members_id{pod=~\"$Replica\"}))",
     "legendFormat": "# members"
    },
    {
     "expr": "count (count by(member_idx)(mongodb_members_health{pod=~\"$Replica\"} == 1))",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "timeseries",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# https://www.mongodb.com/docs/manual/reference/replica-states/\r\nsum by(member_idx) (mongodb_members_state{pod=~\"$Replica\", rs_state=\"1\"})\r\nor\r\navg by(member_idx) (mongodb_members_state{pod=~\"$Replica\"})\r\n",
     "legendFormat": "{{member_idx}} - {{rs_state}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_opcountersRepl_command{pod=~\"$Replica\"}",
     "legendFormat": "{{ pod }} command"
    },
    {
     "expr": "mongodb_opcountersRepl_delete{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}} delete"
    },
    {
     "expr": "mongodb_opcountersRepl_getmore{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}} getmore"
    },
    {
     "expr": "mongodb_opcountersRepl_insert{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}} insert"
    },
    {
     "expr": "mongodb_opcountersRepl_query{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}} query"
    },
    {
     "expr": "mongodb_opcountersRepl_update{pod=~\"$Replica\"}",
     "legendFormat": "{{pod}} update"
    }
   ]
  }
 ]
}