{{- if and .Values.drachtio.config.monitoring.prometheus.enabled (not .Values.useLegacyArch) }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rocketchat-voip.fullname" . }}-drachtio
  labels:
    {{- include "rocketchat-voip.labels" . | nindent 4 }}
    app.kubernetes.io/component: drachtio
spec:
  selector:
    matchLabels:
      {{- include "rocketchat-voip.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: drachtio
  endpoints:
  - port: prometheus-metrics
    interval: 30s
    path: /metrics
{{- end }}
{{- end }}