{{- if not .Values.useLegacyArch }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketchat-voip.fullname" . }}-drachtio
  labels:
    {{- include "rocketchat-voip.labels" . | nindent 4 }}
    app.kubernetes.io/component: drachtio
  annotations:
    {{- with .Values.freeswitch.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.drachtio.config.monitoring.prometheus.enabled (not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")) }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.drachtio.config.monitoring.prometheus.port }}"
    prometheus.io/path: "/metrics"
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: admin
      port: {{ .Values.drachtio.adminPort }}
      targetPort: {{ .Values.drachtio.adminPort }}
      protocol: TCP
    - name: sip-udp
      port: {{ .Values.drachtio.sipPort }}
      targetPort: {{ .Values.drachtio.sipPort }}
      protocol: UDP
    {{- if .Values.drachtio.config.monitoring.prometheus.enabled }}
    - name: prometheus-metrics
      port: {{ .Values.drachtio.config.monitoring.prometheus.port }}
      targetPort: {{ .Values.drachtio.config.monitoring.prometheus.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "rocketchat-voip.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: drachtio
{{- end }}