apiVersion: v1
kind: Secret
metadata:
  name: freeswitch-passwords
type: Opaque
stringData:
  freeswitch_password: "{{ .Values.freeswitch.freeswitchPassword }}"
  extension_password: "{{ .Values.freeswitch.extensionPassword }}"