freeswitch:
  externalAddressRtp: rtp.chat.foobar.org
  externalAddressWebsocket: voip.chat.foobar.org
  # The password used by Rocket.Chat to talk with FreeSWITCH's API 
  freeswitchPassword: "changeme!!!"
  # Default password used to authenticate extensions
  extensionPassword: "changeme!!!"

# Input here a list of extensions you want to use
extensionsFile: 
  listOfExtensions: |
    2112
    8012 8022 8082
    6996
    7770
    6500 9653

image:
  # We're using «stable» by default, you probably don't want 
  # to change this. It exists only for clarity. 
  tag: "stable"

# Adjust those numbers if you're hitting any limits. If not, 
# leave them as they are. You probably can get away with less, 
# albeit not recommended. 
resources:
  requests:
    memory: 4Gi
  limits:
    memory: 8Gi