---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - airlock.cloud.rocket.chat
    resources:
      - mongodbaccessrequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - airlock.cloud.rocket.chat
    resources:
      - mongodbaccessrequests/finalizers
    verbs:
      - update
  - apiGroups:
      - airlock.cloud.rocket.chat
    resources:
      - mongodbaccessrequests/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - airlock.cloud.rocket.chat
    resources:
      - mongodbclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - airlock.cloud.rocket.chat
    resources:
      - mongodbclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - airlock.cloud.rocket.chat
    resources:
      - mongodbclusters/status
    verbs:
      - get
      - patch
      - update
