{{- $failMessage := include "v10_breakingMigrationFailMessage" . -}}
{{- if (include "needsMongodb" .) -}}
{{- template "checkAcknowledgeUpgrade" . -}}
{{- if .Capabilities.APIVersions.Has "mongodbcommunity.mongodb.com/v1/MongoDBCommunity" | not -}}
{{- cat "Mongodb controller not found, must install that before upgrading if mongodb is to be deployed." $failMessage | fail -}}
{{- else -}}
{{- $existingCluster := (lookup "mongodbcommunity.mongodb.com/v1" "MongoDBCommunity" .Release.Namespace (include "rocketchat.mongodb.name" .)) -}}
{{- if empty $existingCluster -}}
{{/*only time we create a cluster, we only verify if there is an existing but let users freely modify the created resource*/}}
{{- range $index, $user := .Values.mongodb.auth.users }}
  {{- if not (index $.Values.mongodb.auth.passwords $user) }}
    {{- fail (printf "Password not found for user '%s' in mongodb.auth.passwords" $user) }}
  {{- end }}
  {{- if not (index $.Values.mongodb.auth.databases $index) }}
    {{- fail (printf "Database not found at index %d for user '%s' in mongodb.auth.databases" $index $user) }}
  {{- end }}
{{- end }}
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ include "rocketchat.mongodb.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  members: {{ .Values.mongodb.replicaCount }}
  type: ReplicaSet
  version: {{ .Values.mongodb.version }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
{{- range $index, $user := .Values.mongodb.auth.usernames }}
    - name: {{ $user }}
      db: {{ index $.Values.mongodb.auth.databases $index }}
      passwordSecretRef:
        name: {{ include "rocketchat.mongodb.name" $ }}-{{ $user }}-password
      roles:
        - name: readWrite
          db: {{ index $.Values.mongodb.auth.databases $index }}
      scramCredentialsSecretName: {{ include "rocketchat.fullname" $ }}-{{ $user }}-scram
{{- end }}
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
{{- if .Values.mongodb.metrics.enabled }}
  prometheus:
    port: 9216
    username: {{ .Values.mongodb.metrics.auth.username }}
    passwordSecretRef:
      name: {{ include "rocketchat.mongodb.name" . }}-metrics-basic-auth
      key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketchat.mongodb.name" . }}-metrics-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.mongodb.metrics.auth.username | b64enc | quote }}
  password: {{ .Values.mongodb.metrics.auth.password| b64enc | quote }}
---

{{- end }}

{{- else -}}
{{- toYaml $existingCluster }}
{{- end -}}

{{- range $index, $username := .Values.mongodb.auth.usernames }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketchat.mongodb.name" $ }}-{{ $username }}-password
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  password: {{ index $.Values.mongodb.auth.passwords $index | b64enc | quote }}
{{- end }}

{{- end -}}
{{- end -}}