{{- if or .Values.opentelemetryCollector.logs.enabled .Values.opentelemetryCollector.events.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-otel-collector-service-account"
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-otel-collector-role"
rules:
- apiGroups: 
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events # both events from core/v1 and events.k8s.io should be enabled
  - namespaces
  - namespaces/status
  - nodes
  - nodes/spec
  - pods
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - resourcequotas
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-otel-collector-binding"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-otel-collector-service-account"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-otel-collector-role"
  apiGroup: rbac.authorization.k8s.io
{{- end -}}