{{- if or .Values.opentelemetryCollector.logs.enabled -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Release.Name }}-opentelemetry-collector-logs-agent"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-opentelemetry-collector-logs-agent"
    app.kubernetes.io/instance: otlp-logs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-opentelemetry-collector-logs-agent"
      app.kubernetes.io/instance: otlp-logs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-opentelemetry-collector-logs-agent"
        app.kubernetes.io/instance: otlp-logs
    spec:
      serviceAccountName: "{{ .Release.Name }}-otel-collector-service-account"
      automountServiceAccountToken: true
      containers:
        - name: opentelemetry-logs-collector
          args:
            - --config=/conf/logs.yaml
          image: "{{ .Values.opentelemetryCollector.image.registry }}:{{ .Values.opentelemetryCollector.image.tag }}"
          imagePullPolicy: "{{ .Values.opentelemetryCollector.image.pullPolicy }}"
          resources:
            {{- toYaml .Values.opentelemetryCollector.logs.resources | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: metrics
              containerPort: 8888
            - name: health-check
              containerPort: 13133
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          volumeMounts:
            - mountPath: /conf
              name: "{{ .Release.Name }}-opentelemetry-collector-config"
            - mountPath: /var/log/pods
              name: varlogpods
              readOnly: true
            - mountPath: /var/log/containers
              name: varlogcontainers
              readOnly: true
            # system-metrics
            - mountPath: /hostfs/var/lib/kubelet
              name: var-lib-kubelet
              readOnly: true
            - mountPath: /hostfs/dev
              name: dev
              readOnly: false
            - mountPath: /hostfs/run/udev
              name: run-udev
              readOnly: true
            - mountPath: /hostfs/sys
              name: sys
              readOnly: true
            - mountPath: /hostfs/proc
              name: proc
              readOnly: true
            - mountPath: /hostfs/boot
              name: boot
              readOnly: true
      volumes:
        - name: "{{ .Release.Name }}-opentelemetry-collector-config"
          configMap:
            name: "{{ .Release.Name }}-opentelemetry-collector-config"
            items:
              - key: logs.yaml
                path: logs.yaml
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: Directory
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
            type: Directory
        # system-metrics
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: dev
          hostPath:
            path: /dev
        - name: run-udev
          hostPath:
            path: /run/udev
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
        - name: boot
          hostPath:
            path: /boot
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Release.Name }}-otel-logs-pod-monitor"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-opentelemetry-collector-logs-agent"
    app.kubernetes.io/instance: otlp-logs
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-opentelemetry-collector-logs-agent"
      app.kubernetes.io/instance: otlp-logs

{{- end -}}