name: Draft new release


env:
  INFO_URL: "https://releases.rocket.chat/latest/info"
  THIS_REPOSITORY: ${{ github.repository }}

on:
  schedule:
    # every day at 6 o'clock
    # # basically every 24 hours
    - cron: "0 6 * * *"


jobs:

  create_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt update -qqq && sudo apt install jq -yqqq

      - name: Get latest release version
        run: |
          info_url=${{ env.INFO_URL }}
          latest_version=$(curl -s "$info_url" | jq -r .tag)
          echo "[DEBUG] LATEST_VERSION: $latest_version"
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Is current helm tag the latest
        id: is_not_latest
        run: |
          current_helm_version="$(
            git -c 'versionsort.suffix=-' ls-remote -t --exit-code --refs --sort=-v:refname "https://github.com/$THIS_REPOSITORY" '*' |
                  sed -En '1!q;s/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/gp'
          )"
          echo "[DEBUG] CURRENT_VERSION: $current_helm_version"
          latest_version=${{ env.LATEST_VERSION }}


          is_gt() {
            local v1=(${1/./ })
            local v2=(${2/./ })

            for _ in $(seq 0 2); do
              (( ${v1[$_]} < ${v2[$_]} )) && return 1
              (( ${v1[$_]} > ${v2[$_]} )) && return 0
            done
          }

          if is_gt "$latest_version" "$current_helm_version"; then
            echo "::set-output name=is_not_latest::true"
          fi

      - name: Draft a new release
        if: ${{ steps.is_not_latest.outputs.is_not_latest }} == "true"
        uses: marvinpinto/action-automatic-releases@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          automatic_release_tag: ${{ env.LATEST_VERSION }}
          title: ${{ env.LATEST_VERSION }}




